image: "ai.b-bug.org:5000/rust:1-rsproxy"

cache:
  - key:
      files:
        - Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1
    paths:
      - Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1

build:
  stage: build
  script:
    - test -d Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1 || (curl -fsSL https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1663142514282/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1-20220906.tar.gz|tar zxvf -)
    - cargo build --target riscv64gc-unknown-linux-gnu --config target.riscv64gc-unknown-linux-gnu.linker=\"./Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1/bin/riscv64-unknown-linux-gnu-gcc\"
    - cargo test --workspace --verbose
  artifacts:
    paths:
      - target/riscv64gc-unknown-linux-gnu/debug/libsvglite.so
