[package]
name = "svglite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usvg = "0.29.0"

[profile.release]
opt-level = "z"
