[package]
name = "svglite"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
test = true

[dependencies]
usvg = "0.29.0"
ttf-parser = "0.18.1"

[profile.release]
opt-level = "z"
