name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup target add riscv64gc-unknown-linux-gnu
        curl -fsSL https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1663142514282/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1-20220906.tar.gz|tar zxvf -
  
    - name: Build
      run: |
        cargo build --target riscv64gc-unknown-linux-gnu --config target.riscv64gc-unknown-linux-gnu.linker=\"./Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.1/bin/riscv64-unknown-linux-gnu-gcc\"
    - name: Run tests
      run: cargo test --verbose
